---
title: "Date generation"
output: pdf_document
date: "2025-05-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(sdcSpatial)
library(gridExtra)
library(dplyr)
library(raster)

plot_func = function(data, title, type){
  
  if(type == "point") func = geom_point()
  if(type == "heatmap") func = ggdensity::geom_hdr(probs = seq(0.01,1-0.01,0.01))
  
  plot = ggplot(data, aes(x, y)) + 
    func + 
    theme_classic()+
    theme(aspect.ratio = 1, legend.position = "none") +
    ggtitle(title)
  
  return(plot)
}
```
https://www.datawim.com/post/generating-different-patterns-in-r/
https://r-spatial.org/book/11-PointPattern.html


## 1. normal density
```{r, fig.align='center'}

### generating data
set.seed(1); n1 = 1000
data1 = data.frame(x = rnorm(n1),y = rnorm(n1))
random1 = mask_random(data1[,1:2], 3)
grid1 = mask_grid(data1[,1:2],0.25)
vonoroi1 = mask_voronoi(data1[,1:2])
weighted1 = mask_weighted_random(data1[,1:2], k=5, r=3)


### defining point plots
data_list <- list(original = data1, 
                  random = random1, 
                  grid = grid1, 
                  vonoroi = vonoroi1, 
                  weighted = weighted1)

pplots1 <- lapply(names(data_list), function(nm) plot_func(data_list[[nm]], nm, "point"))



```

```{r}
### making gridded plots
g.og1 = sdc_raster(data1, var = rep(1, n1), r = 0.2)$value$sum
g.rd1 = sdc_raster(random1, var = rep(1, n1), r = 0.2)$value$sum
g.gr1 = sdc_raster(grid1, var = rep(1, n1), r = 0.2)$value$sum
g.vo1 = sdc_raster(vonoroi1, var = rep(1, n1), r = 0.2)$value$sum
g.we1 = sdc_raster(weighted1, var = rep(1, n1), r = 0.2)$value$sum
par(mfrow = c(2,3))
plot(g.og1, main = "original")
plot(g.rd1, main = "random")
plot(g.gr1, main = "grid")
plot(g.vo1, main = "vonoroi")
plot(g.we1, main = "weighted")


### this works better
grids1 = lapply(names(data_list), function(nm) sdc_raster(data_list[[nm]], var = rep(1, 1000), r = 0.2))
names(grids1) = names(data_list)

lapply(names(grids1), function(nm)  plot(grids1[[nm]]$value$sum, main = nm))




```

heatmaps
```{r}

h.og1 = plot_func(data1, "Original", "heatmap")
h.rd1 = plot_func(random1, "Safe:Random", "heatmap")
h.gr1 = plot_func(grid1, "Safe:Grid", "heatmap")
h.vo1 = plot_func(vonoroi1, "Safe:vonoroi", "heatmap")
h.we1 = plot_func(weighted1, "Safe:weighted random", "heatmap")

grid.arrange(
  h.og1, h.rd1, h.gr1,h.vo1, h.we1,
  ncol = 3
)



### works better
hplots1 <- lapply(names(data_list), function(nm) plot_func(data_list[[nm]], nm, "heatmap"))

```




## 2. two hotspots (one big one small)
```{r}
### defining data
set.seed(1); n2 = 1500
data2 = data.frame(x = c(rnorm(n2*(2/3)), rnorm(n2*(1/3), 4)),y = c(rnorm(n2*(2/3)), rnorm(n2*(1/3), 4)))
random2 = mask_random(data2, 3)
grid2 = mask_grid(data2,0.25)
vonoroi2 = mask_voronoi(data2)
weighted2 = mask_weighted_random(data2, k=5, r=3)

data_list2 <- list(original = data2, 
                  random = random2, 
                  grid = grid2, 
                  vonoroi = vonoroi2, 
                  weighted = weighted2)

### point and heatmaps
pplots2 <- lapply(names(data_list2), function(nm) plot_func(data_list2[[nm]], nm, "point"))
hplots2 <- lapply(names(data_list2), function(nm) plot_func(data_list2[[nm]], nm, "heatmap"))

### and grid maps
grids2 = lapply(names(data_list2), function(nm) sdc_raster(data_list2[[nm]], var = rep(1, n2), r = 0.2))
names(grids2) = names(data_list2)

lapply(names(grids2), function(nm)  plot(grids2[[nm]]$value$sum, main = nm))


```

## 3. ellipse form
```{r}

data3 = data.frame(x = rnorm(2000, 1:4),
                   y = rnorm(2000, 1:4))

ggplot(data3, aes(x, y)) + 
  geom_point()





```

## 4. random pattern
```{r}

data4 = data.frame(x = runif(1000),
                   y = runif(1000))


ggplot(data4, aes(x, y)) + 
  geom_point()



```


## 5. consistent pattern but no clustering
```{r}

data5 = data.frame(x = rep(seq(0,1,0.1), 11),
                   y = sort(rep(seq(0,1,0.1),11)))


ggplot(data5, aes(x, y)) + 
  geom_point()


```


## 6. tiny clusters
```{r}

x = sapply(runif(100), function(x) rnorm(5,x))

data7 = data.frame(x = c(sapply(runif(100), function(x) rnorm(5,x,0.01))),
                   y = c(sapply(runif(100), function(x) rnorm(5,x,0.01))))

ggplot(data7, aes(x, y)) + 
  geom_point()






```


































