---
title: "heatmap stuff"
output: pdf_document
date: "2025-05-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## General Setup
### Libraries/sources
```{r}
# retrieve basic functions for contours and center/scaling
source("hotspot_functions.R")

## libraries
library(dplyr)
library(ggplot2)
library(lidaRtRee)
library(sf)
library(purrr)
library(sdcSpatial)
library(tigers)
library(raster)

```

### Data
Using the data 'dwellings' here, and using random reallocation as SDC method
```{r}
data_og = dwellings[1:5000,1:2]
data_safe = mask_grid(data_og[1:1000,], r = 100)

plot(data_og)
points(data_safe, col = "Red")


map_original = sdc_raster(dwellings[,1:2], dwellings$consumption)
map_safe = protect_smooth(map_original)


ogplot = ggplot(data_og, aes(x = x, y = y)) +
  ggdensity:: geom_hdr()

safeplot = ggplot(data_safe, aes(x = x, y = y)) +
  ggdensity:: geom_hdr()



ggsave("plot_safe.png", plot = safeplot, width = 6, height = 6, dpi = 300)

library(magick)

img1 <- image_read("plot1.png")
img2 <- image_read("plot2.png")

# Convert to grayscale if necessary
img1_gray <- image_convert(img1, colorspace = "gray")
img2_gray <- image_convert(img2, colorspace = "gray")

# Extract pixel values
mat1 <- as.numeric(image_data(img1_gray))
mat2 <- as.numeric(image_data(img2_gray))

```

```{r}

library(MASS)


data1 = data_og
data2 = data_safe


# Define a common grid
xlim <- c(min(data1$x, data2$x), max(data1$x, data2$x))
ylim <- c(min(data1$y, data2$y), max(data1$y, data2$y))
n <- 100  # number of grid points (higher = finer resolution)

# Compute density grids
dens1 <- kde2d(data1$x, data1$y, n = n, lims = c(xlim, ylim))
dens2 <- kde2d(data2$x, data2$y, n = n, lims = c(xlim, ylim))

# Calculate difference matrix
diff_matrix <- dens1$z - dens2$z

library(tidyverse)

diff_df <- expand.grid(x = dens1$x, y = dens1$y) %>%
  mutate(density_diff = as.vector(diff_matrix))

ggplot(diff_df, aes(x = x, y = y, fill = density_diff)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  coord_fixed() +
  theme_minimal()


ggplot(dens1, aes(x = x, y = y)) +
  geom_tile() 


heatmap_func = function(safe, original, measure = c("simple", "ratio", "hedi"), n = 100){
  # n is defines the grid resolution
  
  xlim <- c(min(safe$x, original$x), max(safe$x, original$x))
  ylim <- c(min(safe$y, original$y), max(safe$y, original$y))

  # Compute density grids
  dens1 <- MASS::kde2d(safe$x, safe$y, n = n, lims = c(xlim, ylim))
  dens2 <- MASS::kde2d(original$x, original$y, n = n, lims = c(xlim, ylim))
 
  rdens <- raster(nrows = n, ncol = n, xmn = xlim[1], ymn= ylim[1], xmx = xlim[2], ymx = ylim[2])
  
  if(measure == "hedi") return(mean(abs(dens1$z - dens2$z)))
  else if(measure == "ratio") plot_vals = log(dens2$z / dens1$z)
  else if(measure == "simple") plot_vals = abs(dens1$z - dens2$z)
  
  par(mfrow = c(1,3))
  values(rdens) = dens1$z; plot(rdens) 
  values(rdens) = dens2$z; plot(rdens) 
  values(rdens) = plot_vals; plot(rdens)
    
}



heatmap_func(data_safe, data_og, "simple")

```


1.790210e-14 9.732972e-14 4.397111e-13 1.650719e-12 5.149587e-12 1.335048e-11 2.877041e-11 5.157477e-11 7.708736e-11 9.678148e-11 1.044022e-10 1.029861e-10 1.052443e-10 1.245422e-10 1.626752e-10 2.050108e-10 2.287480e-10 2.188145e-10 1.780665e-10 1.234396e-10 7.323420e-11