---
title: "hotspot_matching"
author: "Sacha van de Hoef"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### creating some hotspots
```{r}
# retrieve basic functions for contours and center/scaling
source("hotspot_functions.R")

## libraries
library(dplyr)
library(ggplot2)
library(lidaRtRee)
library(sf)
library(purrr)
library(sdcSpatial)
library("tigers")

## data
set.seed(1)
df.original <- data.frame(x = c(abs(rnorm(200)), abs(rnorm(200,4))), y = c(abs(rnorm(200)), abs(rnorm(200,4))))
df.safe = mask_random(df.original, r = 0.5)

og.hs = unbounded_hotspots(df.original, minimum = 0.05)
sf.hs = unbounded_hotspots(df.safe, minimum = 0.05)

plot(og.hs$geometry, axes = TRUE, col = "blue")              # the original hotspots
plot(sf.hs$geometry, axes = TRUE, add = TRUE, col = "green") # the safe hotspots
```
have ot make some more polygons to get a good look
```{r}
## data
set.seed(1)
df.original <- data.frame(x = c(abs(rnorm(200)), abs(rnorm(200,4)), abs(rnorm(200,10))), 
                          y = c(abs(rnorm(200)), abs(rnorm(200,4)), abs(rnorm(200,1))))
df.safe = mask_random(df.original, r = 0.5)

og.h = unbounded_hotspots(df.original, minimum = 0.03)
sf.hs = unbounded_hotspots(df.safe, minimum = 0.03)

plot(og.h$geometry, axes = TRUE, col = 1:3)              # the original hotspots
plot(sf.hs$geometry, axes = TRUE, add = TRUE, col = 4:5) # the safe hotspots

```
pink: 2
green: 3
black: 1
------------
dark blue: 1
light blue: 2

So it should be from safe -> original
dark blue -> pink (1 -> 2)
light blue -> black (2 -> 1)
```{r}
s2o = st_nearest_feature(sf.hs$geometry, og.h$geometry)


matches = data.frame("Safe ID" = 1:length(s2o),
           "Closest Og ID" = s2o)


symmetric_diff_function = function(sf.hs1, og.hs1){
  sc.og.hs = scale.center.poly(og.hs1$geometry)
  sc.sf.hs = scale.center.poly(sf.hs1$geometry)
  symdiff1 = st_sym_difference(sc.og.hs, sc.sf.hs)
  
  plot(sc.og.hs, axes = TRUE, col = "blue")              # the original hotspots
  plot(sc.sf.hs, axes = TRUE, add = TRUE, col = "green") # the safe hotspots
  plot(symdiff1, add = TRUE, col = "red")
  
  # the to calculate the area of the symmetric difference
  return(st_area(symdiff1))
}

symmetric_diff_function(sf.hs[1,], og.h[1,]) # seems to work well
```

now for multiple at the same time
```{r}
s2o = st_nearest_feature(sf.hs$geometry, og.h$geometry)

matches = data.frame("Safe ID" = 1:length(s2o),
                     "Closest Og ID" = s2o)



apply(matches, 1, function(x) symmetric_diff_function(sf.hs[x[1],], og.h[x[2],]))

x = 1


```


```{r}
s2o = st_nearest_feature(sf.hs$geometry, og.h$geometry)

matches = data.frame("Safe ID" = 1:length(s2o),
                     "Closest Og ID" = s2o)



apply(matches, 1, function(x) symmetric_diff_function(sf.hs$geometry[x,], og.h$geometry[x,]))




average_measure = function(func, A, B){

  results = apply(matches, 1, function(x) func(A[x[1],], B[x[2],]))
  
  return(results)
}

average_measure(symmetric_diff_function, sf.hs, og.h)
average_measure()


```





```{r}
plot(hotspot_og[6,]$geometry, axes = TRUE, xlim = range(data_og[,1]), ylim = range(data_og[,2]), col = alpha("blue", 0.4))
plot(hotspot_safe[7,]$geometry, add = TRUE, col = alpha("red", 0.4))


plot(hotspot_og[6,]$geometry, axes = TRUE, col = alpha("blue", 0.4))
plot(hotspot_safe[7,]$geometry, add = TRUE, col = alpha("red", 0.4))


```





















